### ISSUE TITLE
Error: /lib64/libc.so.6: version `GLIBC_2.18' not found

### ISSUE THREAD

**Issue by FourCinnamon0** [Brooooooklyn/canvas#384]
There is an issue when I require it:
```
Welcome to Node.js v14.18.1.
Type ".help" for more information.
> const { createCanvas } = require('@napi-rs/canvas')
Uncaught:
Error: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/opc/node_modules/@napi-rs/canvas-linux-x64-gnu/skia.linux-x64-gnu.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18) {
  code: 'ERR_DLOPEN_FAILED'
}
>
```

OS: Oracle Linux 7.2

**Comment by Brooooooklyn** [comment]
Same with https://github.com/Brooooooklyn/canvas/issues/370
