### ISSUE TITLE
Unexpected Token '?'

### ISSUE THREAD

**Issue by FineMustache** [Brooooooklyn/canvas#538]
I'm getting this issue when starting my backend:

C:\Users\Desenvolvimento\Documents\pessoalidades\finebot\node_modules\@napi-rs\canvas\load-image.js:42
        makeRequest(source, resolve, reject, options.maxRedirects ?? MAX_REDIRECTS, options.requestOptions),
                                                                   ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\Desenvolvimento\Documents\pessoalidades\finebot\node_modules\@napi-rs\canvas\index.js:19:19)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    
    
I didn't have it before and I don't know what should i do

**Comment by Brooooooklyn** [comment]
It's [Nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator). It's introduced in Node.js 14. You can upgrade your Node.js to Node 14+ as a workaround. I'll fix it.
