### ISSUE TITLE
loadImage Buffer error

### ISSUE THREAD

**Issue by alanlichen** [Brooooooklyn/canvas#569]
When using loadImage with a url (`Images[item]` is a string url that references an image), I get this error. Note that the library that I am using [directly exports the loadImage function](https://github.com/kyranet/canvas-constructor/blob/main/src/main.ts.template#L2362) from this library.
Code:
```js
const img = await loadImage(Images[item]);
```
```
Error: Failed to create reference from Buffer
    at s (/Users/REDACTED/project/REDACTED/node_modules/canvas-constructor/dist/napi-rs.js:1:9288)
    at Object.execute (/Users/REDACTED/project/REDACTED/src/REDACTED/index.js:28:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.<anonymous> (/Users/REDACTED/project/REDACTED/src/index.js:67:5) {
  code: 'InvalidArg'
}
```

**Comment by alanlichen** [comment]
Huh... thats strange... i can't seem to repro on my own device!

**Comment by alanlichen** [comment]
I don't know what happened, but it works now. I'm not sure what the solution was, if there was any.
