### ISSUE TITLE
Error when using with pdf.js

### ISSUE THREAD

**Issue by BrianSHenderson** [Brooooooklyn/canvas#571]
I am trying to create a canvas with the contents of a pdf file page using pdf.js with the code below:
```
   const { createCanvas } = require('@napi-rs/canvas')
   var PDFJS = require("pdfjs-dist/legacy/build/pdf.js");
  const r = await getObject("nmm-imgpro-pdfs", `automark/${taskid}/${filename}`);
    const typedArray = new Uint8Array(r.Body);
    const pdf = await PDFJS.getDocument({ data: typedArray }).promise;
    const dataUrl = await new Promise((resolve, reject) => {
        pdf.getPage(page).then((page) => {
            const viewport = page.getViewport({ scale: 1.5 });
            const canvas = createCanvas(viewport.width, viewport.height);
            const canvasContext = canvas.getContext("2d");
            page.render({ canvasContext, viewport }).promise.then(() => {
                const dataUrl = canvas.toDataURL("image/jpg", 1);
                return resolve(dataUrl);
            });
        });
    })
```

The `page.render({ canvasContext, viewport }).promise` seems to be causing the problem producing the error below:
```
error - unhandledRejection: TypeError: Cannot read property 'width' of undefined
    at CanvasGraphics.beginDrawing (/Users/brianhenderson/Documents/Documents/Repositories/automark/node_modules/pdfjs-dist/legacy/build/pdf.js:14365:37)
    at InternalRenderTask.initializeGraphics (/Users/brianhenderson/Documents/Documents/Repositories/automark/node_modules/pdfjs-dist/legacy/build/pdf.js:12547:18)
    at /Users/brianhenderson/Documents/Documents/Repositories/automark/node_modules/pdfjs-dist/legacy/build/pdf.js:10705:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
I am using NextJS with this code being in a server side function.  Any help would be greatly appreciated.

**Comment by kfranqueiro** [comment]
At its root, this seems to be because the context object returned by `canvas.getContext("2d")` has an `undefined` value for `canvas` on it, despite typings suggesting it should exist.

I tried forcing it like so, before passing it to pdf.js:

```ts
    // @ts-ignore
    context.canvas = canvas;
```

...but then I get a new error:

```
Error processing lesson 1964 (golden-age-of-china-3b08d85d40c8): TypeError: ctx.getTransform(...).invertSelf is not a function
    at getCurrentTransformInverse (webpack://pdfjs-dist/build/pdf/src/display/display_utils.js:620:51)
    at CanvasGraphics.paintInlineImageXObject (webpack://pdfjs-dist/build/pdf/src/display/canvas.js:3053:7)
    at CanvasGraphics.apply [as paintImageXObject] (webpack://pdfjs-dist/build/pdf/src/display/canvas.js:2993:10)
    at CanvasGraphics.executeOperatorList (webpack://pdfjs-dist/build/pdf/src/display/canvas.js:1231:20)
    at InternalRenderTask._next (webpack://pdfjs-dist/build/pdf/src/display/api.js:3423:37)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

This new error may be particular to the PDF I'm testing with, and a matter of not all functions being supported yet.

**Comment by LZQCN** [comment]
Error: Value is non of these types `CanvasElement`, `SVGCanvas`, `Image`,

https://github.com/mozilla/pdf.js/blob/529906c74f1a53198200be7f61e63f8f94d1a371/src/display/canvas.js#L261
