### ISSUE TITLE
Error: The specified module could not be found.

### ISSUE THREAD

**Issue by KingEZFLOW** [Brooooooklyn/canvas#693]
```
C:\Users\Administrator\Desktop\bot\node_modules\@napi-rs\canvas\js-binding.js:216
    throw loadError
    ^

Error: The specified module could not be found.
\\?\C:\Users\Administrator\Desktop\bot\node_modules\@napi-rs\canvas-win32-x64-msvc\skia.win32-x64-msvc.node
    at Module._extensions..node (node:internal/modules/cjs/loader:1361:18)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\bot\node_modules\@napi-rs\canvas\js-binding.js:63:29)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\bot\node_modules\@napi-rs\canvas\index.js:19:5)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\bot\commands\utility\profile.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10) {
  code: 'ERR_DLOPEN_FAILED'
}
```

I've just transferred my bot from my personal PC to a VPS, I only get this error on my VPS.

**Comment by ahlulmukh** [comment]
how you fix this?
