### ISSUE TITLE
Failed to build skia on Windows 11

### ISSUE THREAD

**Issue by CGQAQ** [Brooooooklyn/canvas#709]
Envs:
```
OS:     Windows 11 (22H2 OS 22621.2134)
MSVC:   Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32537
Nodejs: LTS v18.16.1
Python: 3.11.3
```

Failed with Error:

```
Command: C:/Users/Administrator/AppData/Local/Microsoft/WindowsApps/python3.exe D:/tmp/canvas/skia/gn/find_msvc.py
Returned 9009.
```

But I  have run find_msvc.py manually, it worked perfectly.
```
PS D:\tmp\canvas> python .\skia\gn\find_msvc.py
C:\Program Files\Microsoft Visual Studio\2022\Community\VC
```

<details><summary>Details</summary>
<p>

```
PS D:\tmp\canvas> node .\scripts\build-skia.js
python ./tools/git-sync-deps
Skipping "bin".
...skia\third_party/externals/jinja2 @ ee69aa00ee8536f61db6a451f3858745cf587de6
...\third_party/externals/abseil-cpp @ cb436cf0142b4cbe47aae94223443df7f82e2920
...\skia\third_party/externals/emsdk @ 4a48a752e6a8bef6f222622f2b4926d5eb3bdeb3
...s\skia\third_party/externals/oboe @ b02a12d1dd821118763debec6b83d00a8a0ee419
...kia\third_party/externals/libgav1 @ 0fb779c1e169fe6c229cd1fa9cc6ea6feeb441da
...kia\third_party/externals/highway @ 424360251cdcfc314cfc528f53c872ecd63af0f0
...kia\third_party/externals/libavif @ f49462dc93784bf34148715eee36ab6697ca0b35
...ia\third_party/externals/freetype @ d857bd535b6c7e877f262a9b61ed21ee11b35dab
...skia\third_party/externals/libpng @ 386707c6d19b974ca2e3db7f5c61873813c6fe44
D:\tmp\canvas\skia\buildtools        @ b138e6ce86ae843c42a1a08f37903207bebcca75
...skia\third_party/externals/angle2 @ 84379a5294073b0f702fa0bbe909c93805cc870a
...rd_party/externals/d3d12allocator @ 169895d529dfce00390a20e69c2f516066fe7a3b
...rd_party/externals/vulkan-headers @ c1a8560c5cf5e7bd6dbc71fe69b1a317411c36b8
...\third_party/externals/markupsafe @ 0944e71f4b2cb9a871bcbe353f95e889b64a611a
...skia\third_party/externals/brotli @ 6d03dfbedda1615c4cba1211f8d81735575209c8
...kia\third_party/externals/libwebp @ fd7b5d48464475408d32d2611bdb6947d4246b97
...\skia\third_party/externals/expat @ 441f98d02deafd9b090aea568282b28f66a50e36
...hird_party/externals/egl-registry @ a0bca08de07c7d7651047bedc0b653cfaaa4f2ae
...ia\third_party/externals/harfbuzz @ 09a266236147497bd8149240062c31c16fbc81e3
...skia\third_party/externals/libyuv @ d248929c059ff7629a85333699717d7a677d8d96
...\third_party/externals/microhttpd @ 748945ec6f1c67b7efc934ab0808e1d32f2fb98d
...ird_party/externals/libjpeg-turbo @ ed683925e4897a84b3bffc5c1414c85b97a129a3
...kia\third_party/externals/dng_sdk @ c8d0c9b1d16bfda56f15165d39e0ffa360a11123
...s\skia\third_party/externals/piex @ bb217acdca1cc0c16b704669dd6f91a1b509c406
...\skia\third_party/externals/vello @ ef2630ad9c647b90863cb0915701d54725733968
...skia\third_party/externals/sfntly @ b55ff303ea2f9e26702b514cf6a3196a2e3e2974
...third_party/externals/vulkan-deps @ 90577eb35eea01011e237747e92ee1fbe199d4c3
...skia\third_party/externals/libjxl @ a205468bc5d3a353fb15dae2398a101dff52f2d3
...\skia\third_party/externals/imgui @ 55d35d8387c15bf0cfd71861df67af8cfbda7456
...d_party/externals/opengl-registry @ 14b80ebeab022b2c78f84a573f01028c96075553
...hird_party/externals/vulkan-tools @ ca8bb4ee3cc9afdeca4b49c5ef758bad7cce2c72
...y/externals/vulkanmemoryallocator @ 7de5cc00de50e71a3aab22dea52fbb7ff4efceb6
...third_party/externals/spirv-cross @ 2d3a152081ca6e6bea7093940d0f81088fe4d01c
...s\skia\third_party/externals/zlib @ c876c8f87101c5a75f6014b0f832499afeb65b73
...third_party/externals/spirv-tools @ a63ac9f73d29cd27cdb6e3388d98d1d934e512bb
...s\skia\third_party/externals/dawn @ 0d5e76a2427f1c629a0d709ee0833da43bf79e84
...as\skia\third_party/externals/icu @ a0718d4f121727e30b8d52c7a189ebf5ab52421f
...ird_party/externals/spirv-headers @ 6e09e44cd88a5297433411b2ee52f4cf9f50fa90
...\skia\third_party/externals/wuffs @ a0041ac0310b3156b963e2f2bea09245f25ec073
...third_party/externals/swiftshader @ ae667fe96db9b7f76edea242015d61f293c7210e
...ia\third_party/externals/perfetto @ 93885509be1c9240bc55fa515ceb34811e54a394
Resolving SDK version '3.1.15' to 'sdk-releases-upstream-568a46a9fb7e1f1686a6f7216b3dc976f28d2a79-64bit'
Installing SDK 'sdk-releases-upstream-568a46a9fb7e1f1686a6f7216b3dc976f28d2a79-64bit'..
Skipped installing node-14.18.2-64bit, already installed.
Skipped installing python-3.9.2-nuget-64bit, already installed.
Skipped installing java-8.152-64bit, already installed.
Skipped installing releases-upstream-568a46a9fb7e1f1686a6f7216b3dc976f28d2a79-64bit, already installed.
All SDK components already installed: 'sdk-releases-upstream-568a46a9fb7e1f1686a6f7216b3dc976f28d2a79-64bit'.
Resolving SDK version '3.1.15' to 'sdk-releases-upstream-568a46a9fb7e1f1686a6f7216b3dc976f28d2a79-64bit'
Setting the following tools as active:
   node-14.18.2-64bit
   python-3.9.2-nuget-64bit
   java-8.152-64bit
   releases-upstream-568a46a9fb7e1f1686a6f7216b3dc976f28d2a79-64bit

Adding directories to PATH:
PATH += D:\tmp\canvas\skia\third_party\externals\emsdk
PATH += D:\tmp\canvas\skia\third_party\externals\emsdk\node\14.18.2_64bit\bin
PATH += D:\tmp\canvas\skia\third_party\externals\emsdk\upstream\emscripten

Setting environment variables:
PATH = D:\tmp\canvas\skia\third_party\externals\emsdk;D:\tmp\canvas\skia\third_party\externals\emsdk\node\14.18.2_64bit\bin;D:\tmp\canvas\skia\third_party\externals\emsdk\upstream\emscripten;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX86\x86;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\VCPackages;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\bin\Roslyn;C:\Program Files\Microsoft Visual Studio\2022\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools;C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\\x86;C:\Program Files (x86)\Windows Kits\10\bin\\x86;C:\Program Files\Microsoft Visual Studio\2022\Community\\MSBuild\Current\Bin\amd64;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\;C:\Python311\Scripts\;C:\Python311\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\ProgramData\chocolatey\bin;C:\Users\Administrator\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\Program Files\Git\cmd;C:\Program Files\LLVM\bin;C:\Users\Administrator\scoop\shims;C:\Users\Administrator\.console-ninja\.bin;C:\Users\Administrator\.cargo\bin;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Users\Administrator\AppData\Local\JetBrains\Toolbox\scripts;C:\ProgramData\chocolatey\lib\deno;C:\Users\Administrator\AppData\Local\gitkraken\bin;C:\Users\Administrator\.dotnet\tools;C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\Linux\bin\ConnectionManagerExeD:\tmp\canvas\depot_tools;D:\tmp\canvas\depot_tools
EMSDK = D:/tmp/canvas/skia/third_party/externals/emsdk
EM_CONFIG = D:\tmp\canvas\skia\third_party\externals\emsdk\.emscripten
EMSDK_NODE = D:\tmp\canvas\skia\third_party\externals\emsdk\node\14.18.2_64bit\bin\node.exe
EMSDK_PYTHON = D:\tmp\canvas\skia\third_party\externals\emsdk\python\3.9.2-nuget_64bit\python.exe
JAVA_HOME = D:\tmp\canvas\skia\third_party\externals\emsdk\java\8.152_64bit
The changes made to environment variables only apply to the currently running shell instance. Use the 'emsdk_env.bat' to re-enter this environment later, or if you'd like to register this environment permanently, rerun this command with the option --permanent.
bin\gn gen out\Static --args='is_official_build=true is_component_build=false is_debug=false werror=false paragraph_gms_enabled=false paragraph_tests_enabled=false skia_enable_android_utils=false skia_enable_discrete_gpu=false skia_enable_gpu=false skia_enable_pdf=true skia_enable_skottie=false skia_enable_skshaper=true skia_enable_tools=false skia_enable_svg=true skia_enable_skparagraph=true skia_enable_sktext=true skia_pdf_subset_harfbuzz=true skia_use_expat=true skia_use_system_expat=false skia_use_gl=false skia_use_harfbuzz=true skia_use_icu=true skia_use_sfntly=false skia_use_libheif=true skia_use_libjpeg_turbo_decode=true skia_use_libjpeg_turbo_encode=true skia_use_libwebp_decode=true skia_use_libwebp_encode=true skia_use_freetype=true skia_use_freetype_woff2=true skia_use_fontconfig=false skia_use_x11=false skia_use_wuffs=true skia_use_system_freetype2=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false skia_use_system_icu=false skia_use_system_harfbuzz=false skia_use_lua=false skia_use_piex=false skia_enable_fontmgr_custom_directory=true skia_enable_fontmgr_custom_embedded=false skia_enable_fontmgr_custom_empty=true skia_enable_fontmgr_android=false skia_enable_fontmgr_win=false skia_fontmgr_factory=\":fontmgr_custom_directory_factory\" cc=\"clang-cl\" cxx=\"clang-cl\" extra_cflags_cc=[\"/std:c++17\",\"/MT\",\"-DSK_FORCE_RASTER_PIPELINE_BLITTER\",\"-DSK_ENABLE_SVG\",\"-DSK_RELEASE\",\"-DSK_DISABLE_TRACING\",\"-DSK_ENCODE_WEBP\",\"-DSK_CODEC_DECODES_WEBP\",\"-DSK_ENCODE_PNG\",\"-DSK_CODEC_DECODES_PNG\",\"-DSK_ENCODE_JPEG\",\"-DSK_CODEC_DECODES_JPEG\",\"-DSK_HAS_HEIF_LIBRARY\",\"-DSK_SHAPER_HARFBUZZ_AVAILABLE\"] clang_win=\"C:\\Program Files\\LLVM\"'
ERROR at //gn/BUILDCONFIG.gn:138:14: Script returned non-zero exit code.
    win_vc = exec_script("//gn/find_msvc.py", [], "trim string")
             ^----------
Current dir: D:/tmp/canvas/skia/out/Static/
Command: C:/Users/Administrator/AppData/Local/Microsoft/WindowsApps/python3.exe D:/tmp/canvas/skia/gn/find_msvc.py
Returned 9009.
node:child_process:960
    throw err;
    ^

Error: Command failed: bin\gn gen out\Static --args='is_official_build=true is_component_build=false is_debug=false werror=false paragraph_gms_enabled=false paragraph_tests_enabled=false skia_enable_android_utils=false skia_enable_discrete_gpu=false skia_enable_gpu=false skia_enable_pdf=true skia_enable_skottie=false skia_enable_skshaper=true skia_enable_tools=false skia_enable_svg=true skia_enable_skparagraph=true skia_enable_sktext=true skia_pdf_subset_harfbuzz=true skia_use_expat=true skia_use_system_expat=false skia_use_gl=false skia_use_harfbuzz=true skia_use_icu=true skia_use_sfntly=false skia_use_libheif=true skia_use_libjpeg_turbo_decode=true skia_use_libjpeg_turbo_encode=true skia_use_libwebp_decode=true skia_use_libwebp_encode=true skia_use_freetype=true skia_use_freetype_woff2=true skia_use_fontconfig=false skia_use_x11=false skia_use_wuffs=true skia_use_system_freetype2=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false skia_use_system_icu=false skia_use_system_harfbuzz=false skia_use_lua=false skia_use_piex=false skia_enable_fontmgr_custom_directory=true skia_enable_fontmgr_custom_embedded=false skia_enable_fontmgr_custom_empty=true skia_enable_fontmgr_android=false skia_enable_fontmgr_win=false skia_fontmgr_factory=\":fontmgr_custom_directory_factory\" cc=\"clang-cl\" cxx=\"clang-cl\" extra_cflags_cc=[\"/std:c++17\",\"/MT\",\"-DSK_FORCE_RASTER_PIPELINE_BLITTER\",\"-DSK_ENABLE_SVG\",\"-DSK_RELEASE\",\"-DSK_DISABLE_TRACING\",\"-DSK_ENCODE_WEBP\",\"-DSK_CODEC_DECODES_WEBP\",\"-DSK_ENCODE_PNG\",\"-DSK_CODEC_DECODES_PNG\",\"-DSK_ENCODE_JPEG\",\"-DSK_CODEC_DECODES_JPEG\",\"-DSK_HAS_HEIF_LIBRARY\",\"-DSK_SHAPER_HARFBUZZ_AVAILABLE\"] clang_win=\"C:\\Program Files\\LLVM\"'
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at exec (D:\tmp\canvas\scripts\build-skia.js:20:3)
    at Object.<anonymous> (D:\tmp\canvas\scripts\build-skia.js:248:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 14064,
  stdout: null,
  stderr: null
}

Node.js v18.16.1
```

</p>
</details>

**Comment by Brooooooklyn** [comment]
is this related? https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/1423

**Comment by Brooooooklyn** [comment]
You can run `node ./scripts/release-skia-binary.js --download` to skip skia build on local

**Comment by CGQAQ** [comment]
I have python in my PATH

![image](https://github.com/Brooooooklyn/canvas/assets/15936231/2cd0d0a4-cdc2-477f-899f-1e89e2c766f8)
