### ISSUE TITLE
Error when `creatingCanvas(0, 0)`(Create skia surface failed)

### ISSUE THREAD

**Issue by yisibl** [Brooooooklyn/canvas#713]
```js
const { createCanvas } = require('@napi-rs/canvas')
const canvas = createCanvas(0, 0)

console.info('canvas', canvas)
```

```shell
return isSvgBackend ? new SVGCanvas(width, height, flag) : new CanvasElement(width, height)
                                                             ^

Error: Create skia surface failed
    at createCanvas (/Users/yisi/works/canvas/index.js:67:62)
    at Object.<anonymous> (/Users/yisi/works/canvas/example/simple.js:3:16)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {
  code: 'GenericFailure'
}
```

**Comment by yisibl** [comment]
Also, we might want to consider fallback to the default 350*150 when there is no aspect value. this is consistent with browsers and [skia-canvas](https://github.com/samizdatco/skia-canvas)

**Comment by alimoezzi** [comment]
I'm having this issue when using it together with pdf.js

**Comment by ImLunaHey** [comment]
@Brooooooklyn was this fixed? (if so in which release/commit?)

**Comment by twlite** [comment]
> @Brooooooklyn was this fixed? (if so in which release/commit?)

https://github.com/Brooooooklyn/canvas/pull/739
