### ISSUE TITLE
error: Create skia surface failed in a docker context

### ISSUE THREAD

**Issue by deRockerTom** [Brooooooklyn/canvas#826]
Hi ! I'm currently working on a discord bot and I have a strange behavior when I try to run the app in a docker container. Everything works fine outside of the container, but when I run my app within it, I get this strange error:

```
bot_1  | 62 |   return new DOMMatrix([a, b, c, d, e, f])
bot_1  | 63 | }
bot_1  | 64 | 
bot_1  | 65 | function createCanvas(width, height, flag) {
bot_1  | 66 |   const isSvgBackend = typeof flag !== 'undefined'
bot_1  | 67 |   return isSvgBackend ? new SVGCanvas(width, height, flag) : new CanvasElement(width, height)
bot_1  |                                                                                                                       ^
bot_1  | error: Create skia surface failed
bot_1  |  code: "GenericFailure"
bot_1  | 
bot_1  |       at createCanvas (/home/bun/app/node_modules/@napi-rs/canvas/index.js:67:62)
bot_1  |       at /home/bun/app/src/core/challenges/challengeImage.ts:70:12
bot_1  |       at buildImage (/home/bun/app/src/core/challenges/challengeImage.ts:8:3)
bot_1  |       at /home/bun/app/src/core/challenges/index.ts:95:24
```

Here is my Dockerfile if you need it, but I don't do much in it:
```Dockerfile
ARG BUN_VERSION

FROM oven/bun:${BUN_VERSION}-alpine

# Copy the lock and package file
COPY bun.lockb .
COPY package.json .
COPY tsconfig.json .

# Install dependencies
RUN bun install

# Copy source code
COPY src ./src

CMD ["bun", "src/index.ts"]
```

If someone has any idea on how to make it work it would be really helpful for me, as I'm trying to see what's happening since yesterday :(

**Comment by deRockerTom** [comment]
Found the fix. It was my fault, needed to add
```
RUN apt-get update
RUN apt-get install -y -q --no-install-recommends libfontconfig1
```
for it to work
